apiVersion: v1
kind: Service
metadata:
  name: chronograf
  namespace: flink
spec:
  type: LoadBalancer
  ports:
  - port: 8888
    name: http
    targetPort: 8888
    protocol: TCP
  selector:
    app: chronograf