apiVersion: v1
kind: Service
metadata:
  name: jobmanager
  namespace: flink
spec:
  selector:
    component: jobmanager
  ports:
    - name: rpc
      port: 6123
    - name: blob
      port: 6124
    - name: query
      port: 6125

