apiVersion: v1
kind: Service
metadata:
  name: jobmanager-webui
  namespace: flink
spec:
  type: LoadBalancer
  selector:
    component: jobmanager
  ports:
    - port: 8081
      targetPort: 8081
      name: http
  
